version: "3"
services:
  db:
    image: mariadb:10.5.4-focal 
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION",
      ]
  # flask:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - FLASK_APP=demo.py
  #   command: bash -c "flask run"
  #   volumes:
  #     - .:/flask
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db